# This is a config file for the insomnia - endpoints & their properties
insomnia:
  target-group:
      - label:  "network"
        targets: 
          - endpoint:
              url: "https://fast.com"    
              interval: 1 # only whole numbers for v1 
              unit: "m" # - in s, m, h ( default - m ) - only fixed values allowed on the cli
          - endpoint:
              url: "https://whatismyipaddress.com"
              interval: 1
              unit: "m"

      - label:  "utility"
        targets: 
          - endpoint:
              url: "https://www.youtube.com/"    
              interval: 2
              unit: "m"
          - endpoint:
              url: "https://www.google.com/"
              interval: 2
              unit: "m"

      - label:  "ai"
        targets: 
          - endpoint:
              url: "https://chatgpt.com/"    
              interval: 3
              unit: "m"  
  # global-setting: ( planning to add this later )